### ISSUE TITLE
✨Consulting Pages - Development Teams

### ISSUE THREAD

**Issue by ozairashfaqueSSW** [SSWConsulting/SSW.Website.Content#19]
Cc: @AttackOnMorty @pierssinclairssw @adamstephensen 

To Myself,
  
### Pain

We need to migrate the existing Consulting pages of the Development Teams category

### Tasks

- [ ] [Add Web Applications](https://www.ssw.com.au/ssw/Consulting/Web-Applications.aspx)
- [ ] [Add Mobile Apps](https://www.ssw.com.au/ssw/Consulting/Mobile-Application-Development.aspx)
- [ ] [Angular](https://www.ssw.com.au/ssw/Consulting/Angular.aspx)
- [ ] [Add React](https://www.ssw.com.au/ssw/Consulting/React.aspx)
- [ ] [Add Blazor](https://www.ssw.com.au/ssw/Consulting/Blazor.aspx)
- [ ] [Add Vue](https://www.ssw.com.au/ssw/Consulting/Vuejs.aspx)
- [ ] [Add Bots](https://www.ssw.com.au/ssw/Consulting/Bots.aspx)
- [ ] [Add Database Development](https://www.ssw.com.au/ssw/Consulting/Database-Development.aspx)
- [ ] [Add Enterprise Reporting and BI](https://www.ssw.com.au/ssw/Consulting/Enterprise-Reporting.aspx)
- [ ] [Add Power BI](https://www.ssw.com.au/ssw/Consulting/Power-BI.aspx)
- [ ] [Add Windows Desktop Applications](https://www.ssw.com.au/ssw/Consulting/Desktop-Development.aspx)
- [ ] [Add Azure Synapse](https://www.ssw.com.au/ssw/Consulting/Azure-Synapse.aspx)

Thanks!

**Comment by ozairashfaqueSSW** [comment]
> - [x] [React](https://www.ssw.com.au/ssw/Consulting/React.aspx)

Done - see
![image](https://user-images.githubusercontent.com/96504411/156084273-40fcf8e9-644e-40d2-a159-4bb4844560ae.png)
**Figure: React page added in consulting**

**Comment by ozairashfaqueSSW** [comment]
> - [x] [Vue](https://www.ssw.com.au/ssw/Consulting/Vuejs.aspx)

Done - see
![image](https://user-images.githubusercontent.com/96504411/156085676-c58f13d4-7ce8-48b5-976a-fdf05436e355.png)
**Figure: Vue page is added in consulting services**
