### ISSUE TITLE
✨Migration - Products pages

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Website.Content#4]
Cc: @adamcogan @pierssinclairssw @christianmorfordwaitessw  @tiagov8 

To Myself
  
### Pain
We need to migrate the existing Products pages.

### Tasks

- [ ] Investigate the existing products pages
- [ ] Mark all pages approved for migration
- [ ] Add the content to the new Gatsby site

### Screenshots

Thanks!
