### ISSUE TITLE
✨ Consulting pages - Remote Work and Zendesk pages unique content

### ISSUE THREAD

**Issue by bigtony97** [SSWConsulting/SSW.Website.Content#46]
Cc: @lukecookssw @tkapa @pierssinclairssw @ozairashfaqueSSW @paulsmythssw @kevinpho2022 

To Myself
  
### Pain

We need to modify the consulting page template to account for unique content in the Remote work and Zendesk pages

### Tasks

- [ ] Remote Work Page - Investigate the best way to include unique content into the template
- [ ] Zendesk - Investigate the best way to include unique content into the template
- [ ] Action solutions to unique content

### More Information

The [remote work](https://www.ssw.com.au/ssw/Consulting/Remote-Work.aspx) page has a unique content section under the Technologies section. The [Zendesk ](https://www.ssw.com.au/ssw/Consulting/Zendesk.aspx) page has unique content in the hero banner and has a different technologies section call "Zendesk solutions".

### Screenshots

![image](https://user-images.githubusercontent.com/71110132/164390651-9a031d21-d6f1-47b5-bdbd-e295889a3285.png)
**Figure: Remote work unique content under technologies section**

![image](https://user-images.githubusercontent.com/71110132/164390509-c2420f48-c67d-430e-813f-fdf0b48e6e1d.png)
**Figure: Zendesk hero banner content**

![image](https://user-images.githubusercontent.com/71110132/164390348-c4a5dd02-7954-4e46-90cc-d0718d4b94a1.png)
**Figure: Zendesk solutions section**
Thanks!

**Comment by lukecookssw** [comment]
@bigtony97 
The Zendesk page was discussed a few weeks ago, before we changed templates to use the markdown body. @tiagov8 was satisfied with changing the Hero banner to match the existing template.

Please ping him tomorrow before 11am, and discuss this issue with him and @pierssinclairssw to see if you can come to an agreement on how best to continue. For instance, he may be happy to move that additional content in 'remote-work' up to the main body section.
The 'Zendesk solutions' shouldn't be *too hard* to incorporate into the template, as those flip-out components are pretty much the same as the 'Other technologies' we already use. We may just need to push the header out into the content files as well. Again - discuss this with Tiago and Piers.
