### ISSUE TITLE
✨Migration - Training pages

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Website.Content#5]
Cc: @adamcogan @pierssinclairssw @christianmorfordwaitessw  @tiagov8 

To Myself
  
### Pain
We need to migrate the existing Training pages.

### Tasks

- [ ] Investigate the existing training pages
- [ ] Mark all pages approved for migration
- [ ] Add the content to the new Gatsby site

Thanks!
