### ISSUE TITLE
✨Migration - User Groups pages

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Website.Content#6]
Cc: @adamcogan @pierssinclairssw @christianmorfordwaitessw  @tiagov8 

To Myself
  
### Pain
We need to migrate the existing User Groups pages.

### Tasks

- [ ] Investigate the existing User Groups pages
- [ ] Mark all pages approved for migration
- [ ] Add the content to the new Gatsby site

Thanks!
