### ISSUE TITLE
✨ Migration - About Us pages

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Website.Content#7]
Cc: @adamcogan @pierssinclairssw @christianmorfordwaitessw  @tiagov8 

To Myself
  
### Pain
We need to migrate the existing About Us pages.

### Tasks

- [ ] Investigate the existing About Us pages
- [ ] Mark all pages approved for migration
- [ ] Add the content to the new Gatsby site

Thanks!
