### ISSUE TITLE
✨Update all Technology thumbnails

### ISSUE THREAD

**Issue by ozairashfaqueSSW** [SSWConsulting/SSW.Website.Content#73]
Cc: @adamcogan @pierssinclairssw @lukecookssw @steven0x51 @christianmorfordwaitessw 

To Myself
  
### Pain

Many technology thumbnails are missing. Need to add all of them from all consulting pages.
### Tasks

- [ ] Find the missing thumbnails
- [ ] Upload all of them
- [ ] Delete image path from [technologies](https://github.com/SSWConsulting/SSW.Website.Content/tree/staging/technologies) logoImage frontmatter key/value pair
- [ ] Provide relevant key for logoImage frontmatter key/value pair on all mdx files in [technologies]

Thanks!
