### ISSUE TITLE
♻️ Consulting Pages / Technologies markdown files 

### ISSUE THREAD

**Issue by ozairashfaqueSSW** [SSWConsulting/SSW.Website.Content#77]
Cc: @adamcogan @pierssinclairssw @lukecookssw @ozairashfaqueSSW 

Hi @steven0x51 

### Pain

Currently, we are using the technologies keyword in frontmatter for adding new services on our pages as it is very confusing. Frontmatter key-value pair Technologies need to be changed in all mark down files of [consulting source](https://github.com/SSWConsulting/SSW.Website.Content/tree/staging/consulting) 

### Tasks

- [x] Rename technologies to technologyCards in all markdown files of consulting
- [x] Remove all logos from image directory of technologies
- [x] Remove frontmatter logoImage key-value

### Screenshots

![image](https://user-images.githubusercontent.com/96504411/179126377-34539c89-f0f5-42ae-b2bd-550569f8a56a.png)
**Figure: technologies Key is confusing**

![image](https://user-images.githubusercontent.com/96504411/179668323-fec9486b-8188-4a91-97de-526b975d67a6.png)
**Figure: logo images are no longer added to technologies/images directory**

![image](https://user-images.githubusercontent.com/96504411/179668128-ed4a1828-ba60-431a-bd85-14fd254b0814.png)
**Figure: logoImage key-value pair is not needed anymore**

Thanks!
